### ISSUE TITLE
Feature request: Implement use of term.control so spinners don't interfer with eachother.

### ISSUE THREAD

**Issue by JDoawp** [rhygg/spinners#3]
Right now if you launch two threads of the same method both using spinners they'll "overlap" each other until one of them is done.

With the implementation of the terminal controls from term.control I believe you should be able to make so each spinner keeps track of it's own position to then move the cursor to its own row before updating itself. After a spinner has updated the cursor should probably be moved to the end of terminal in case anything else needs to write.

**Comment by rhygg** [comment]
I'm not really sure if that's possible with the current implementation, you'll have to wait for one spinner to complete, for the other one to work without overlapping. All we can do for the time being is prevent the existence of multiple spinners.

If you do figure out a way, open a pull request & I'll be more than happy to merge it 😄

**Comment by JDoawp** [comment]
> I'm not really sure if that's possible with the current implementation, you'll have to wait for one spinner to complete, for the other one to work without overlapping. All we can do for the time being is prevent the existence of multiple spinners.
> 
> If you do figure out a way, open a pull request & I'll be more than happy to merge it smile

Understandable, I've been looking through the docs and there doesn't seem to be a way to figure out which line you are on in the terminal, not that I can see at least.
